# Set SHELL to 'strict mode' without using .SHELLFLAGS for max compatibility.
# See https://fieldnotes.tech/how-to-shell-for-compatible-makefiles/
SHELL := /usr/bin/env bash -euo pipefail -c

CONFIG         := config.yml
CONFIG_PACKED  := config-packed

.PHONY: ci-config
ci-config: $(CONFIG)

ci-verify: config-up-to-date

define GENERATED_FILE_HEADER
### ***
### WARNING: DO NOT manually EDIT or MERGE this file, it is generated by 'make ci-config'.
### INSTEAD: Edit or add files in subdirectories next to this file, then run 'make ci-config'.
### ***
endef
export GENERATED_FILE_HEADER

.PHONY: $(CONFIG)
$(CONFIG): $(CONFIG_PACKED)
	@mv -f $(CONFIG_PACKED) $@
	@echo "$@ updated"

.PHONY: $(CONFIG_PACKED)
$(CONFIG_PACKED):
	@cp $(CONFIG) @$(CONFIG)
	@echo "$$GENERATED_FILE_HEADER" > $(CONFIG_PACKED)
	@$(CIRCLECI_CLI) config pack . >> $(CONFIG_PACKED)
	@rm -f @$(CONFIG)

.PHONY: config-up-to-date
config-up-to-date: $(CONFIG_PACKED)
	@if diff $(CONFIG) $<; then \
		echo "Generated $(CONFIG) is up to date!"; \
	else \
		echo "Generated $(CONFIG) is out of date, run make $(CONFIG) to update."; \
		exit 1; \
	fi

